// <auto-generated />
using System;
using CostTracker.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CostTracker.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(CostTrackerDbContext))]
    [Migration("20260426193728_AddPlanningGoals")]
    partial class AddPlanningGoals
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CostTracker.Domain.Entities.CategoryBudget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<int>("DisplayOrder")
                        .HasColumnType("integer")
                        .HasColumnName("display_order");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("group_name");

                    b.Property<Guid>("MonthId")
                        .HasColumnType("uuid")
                        .HasColumnName("month_id");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<decimal>("PlannedAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("planned_amount");

                    b.HasKey("Id");

                    b.HasIndex("MonthId", "Name")
                        .IsUnique();

                    b.ToTable("category_budgets", null, t =>
                        {
                            t.HasCheckConstraint("ck_category_budgets_planned_amount_non_negative", "planned_amount >= 0");
                        });
                });

            modelBuilder.Entity("CostTracker.Domain.Entities.Entry", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<decimal>("Amount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("amount");

                    b.Property<Guid>("CategoryBudgetId")
                        .HasColumnType("uuid")
                        .HasColumnName("category_budget_id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)")
                        .HasColumnName("description");

                    b.Property<DateOnly>("EntryDate")
                        .HasColumnType("date")
                        .HasColumnName("entry_date");

                    b.Property<Guid>("MonthId")
                        .HasColumnType("uuid")
                        .HasColumnName("month_id");

                    b.HasKey("Id");

                    b.HasIndex("CategoryBudgetId");

                    b.HasIndex("MonthId", "EntryDate");

                    b.ToTable("entries", null, t =>
                        {
                            t.HasCheckConstraint("ck_entries_amount_non_negative", "amount >= 0");
                        });
                });

            modelBuilder.Entity("CostTracker.Domain.Entities.GroupTarget", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("GroupName")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("group_name");

                    b.Property<Guid>("MonthId")
                        .HasColumnType("uuid")
                        .HasColumnName("month_id");

                    b.Property<decimal>("TargetPercent")
                        .HasColumnType("numeric(5,4)")
                        .HasColumnName("target_percent");

                    b.HasKey("Id");

                    b.HasIndex("MonthId", "GroupName")
                        .IsUnique();

                    b.ToTable("group_targets", (string)null);
                });

            modelBuilder.Entity("CostTracker.Domain.Entities.Month", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid?>("ClonedFromMonthId")
                        .HasColumnType("uuid")
                        .HasColumnName("cloned_from_month_id");

                    b.Property<DateTimeOffset?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(3)
                        .HasColumnType("character varying(3)")
                        .HasColumnName("currency");

                    b.Property<string>("ReferenceMonth")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("character varying(7)")
                        .HasColumnName("reference_month");

                    b.Property<decimal>("Salary")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("salary");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("character varying(16)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ReferenceMonth")
                        .IsUnique();

                    b.HasIndex("Status")
                        .IsUnique()
                        .HasFilter("\"status\" = 'OPEN'");

                    b.ToTable("months", (string)null);
                });

            modelBuilder.Entity("CostTracker.Domain.Entities.PlanningGoal", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at");

                    b.Property<int>("Months")
                        .HasColumnType("integer")
                        .HasColumnName("months");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("character varying(128)")
                        .HasColumnName("name");

                    b.Property<decimal>("SavedAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("saved_amount");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("numeric(12,2)")
                        .HasColumnName("total_amount");

                    b.HasKey("Id");

                    b.ToTable("planning_goals", null, t =>
                        {
                            t.HasCheckConstraint("ck_planning_goals_months_positive", "months >= 1");

                            t.HasCheckConstraint("ck_planning_goals_saved_amount_non_negative", "saved_amount >= 0");

                            t.HasCheckConstraint("ck_planning_goals_total_amount_non_negative", "total_amount >= 0");
                        });
                });

            modelBuilder.Entity("CostTracker.Domain.Entities.CategoryBudget", b =>
                {
                    b.HasOne("CostTracker.Domain.Entities.Month", "Month")
                        .WithMany("CategoryBudgets")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Month");
                });

            modelBuilder.Entity("CostTracker.Domain.Entities.Entry", b =>
                {
                    b.HasOne("CostTracker.Domain.Entities.CategoryBudget", "CategoryBudget")
                        .WithMany("Entries")
                        .HasForeignKey("CategoryBudgetId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CostTracker.Domain.Entities.Month", "Month")
                        .WithMany("Entries")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CategoryBudget");

                    b.Navigation("Month");
                });

            modelBuilder.Entity("CostTracker.Domain.Entities.GroupTarget", b =>
                {
                    b.HasOne("CostTracker.Domain.Entities.Month", "Month")
                        .WithMany("GroupTargets")
                        .HasForeignKey("MonthId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Month");
                });

            modelBuilder.Entity("CostTracker.Domain.Entities.CategoryBudget", b =>
                {
                    b.Navigation("Entries");
                });

            modelBuilder.Entity("CostTracker.Domain.Entities.Month", b =>
                {
                    b.Navigation("CategoryBudgets");

                    b.Navigation("Entries");

                    b.Navigation("GroupTargets");
                });
#pragma warning restore 612, 618
        }
    }
}
